Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [2]:
import numpy as np
def vandermonde_matrix(m, N, increasing = False):
        if increasing == True:
            new_shape =  np.reshape([[i ** j  for j in range(N)]  for i in m], (m.size, N))
        else:
            new_shape = np.reshape([[i ** j  for j in range(N-1,-1,-1)]  for i in m], (m.size, N))
        return new_shape
    
m = np.array([1,2,3,5])
N = 3

decreasing_order_matrix = vandermonde_matrix(m, N)
increasing_order_matrix = vandermonde_matrix(m, N, True)

print("The input array is: {} {}".format(m, "\n"))
print(f"The number of columns in output matrix will be {N} \n")
print(f"Vandermonde matrix result (descreasing order)\n {decreasing_order_matrix}\n")
print(f"Vandermonde matrix result (increasing order) \n {increasing_order_matrix} \n")

The input array is: [1 2 3 5] 

The number of columns in output matrix will be 3 

Vandermonde matrix result (descreasing order)
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]

Vandermonde matrix result (increasing order) 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]] 



Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
import numpy as np
arr1 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3
lst1 = []

def calculate_moving_average(arr1, window):
    counter = 0
    for i in range(0, arr1.size):
        custom_lst = arr1[i:i+window]
        if custom_lst.size == 3:
            x = round(sum(custom_lst)/window,2)
            lst1.append(x)
            counter += 1
    return counter

moving_average = calculate_moving_average(arr1, window)
print(f"The moving average sequence has {moving_average} values.")
print(f"The iterated values are : {lst1}")

The moving average sequence has 11 values.
The iterated values are : [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
